"""add email verification

Revision ID: 924fee2d4254
Revises: ec2b1f8beb8e
Create Date: 2023-05-21 15:05:00.302058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924fee2d4254'
down_revision = 'ec2b1f8beb8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
